### ISSUE TITLE
project is missing a key file

### ISSUE THREAD

**Issue by fabkebab** [FacerTest/poll-blogger#23]
The project is missing a file "tourny_data.json"

meaning that the project cannot be run. Can you add an example into the git repository so the program will run?

**Comment by FacerTest** [comment]
The file is automatically created by the program when a new tournament is started (by inputting a negative round at the beginning dialogue).

While I could theoretically add an example tourny_data.json file, I do not see the point, as it would very quickly be deleted and overwritten by just using the program.

**Comment by fabkebab** [comment]
no so - I ran it twice and it crashed

**Comment by fabkebab** [comment]
oh - why a -ve round?
